/* Generated by GOB (v2.0.16)   (do not edit directly) */

#ifndef __EC_PROGRESS_PRIVATE_H__
#define __EC_PROGRESS_PRIVATE_H__

#include "ec-progress.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _EcProgressPrivate {
#line 14 "ec-progress.gob"
	char * label_text;
#line 18 "ec-progress.gob"
	GdkPixbuf * progress_pixbuf;
#line 20 "ec-progress.gob"
	GdkPixbuf * bg_pixbuf;
#line 23 "ec-progress.gob"
	GdkPixbuf * progress_bg_pixbuf;
#line 26 "ec-progress.gob"
	gboolean use_markup;
#line 74 "ec-progress.gob"
	gdouble progress_val;
#line 98 "ec-progress.gob"
	gint margin_x;
#line 115 "ec-progress.gob"
	gint margin_y;
#line 132 "ec-progress.gob"
	gint progress_margin_y;
#line 149 "ec-progress.gob"
	GtkWidget * label;
#line 150 "ec-progress.gob"
	GtkWidget * event_box;
#line 151 "ec-progress.gob"
	GtkWidget * progress;
#line 38 "ec-progress-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
